### ISSUE TITLE
Crash - missing package react-native-reanimated 

### ISSUE THREAD

**Issue by paskowski** [elyalvarado/react-navigation-switch-transitioner#5]
I am new to React Native ecosystem so I don't know how to explain it properly, but after installing this library through the npm the app started crashing because react-native-reanimated was used, but was not installed. After installing react-native-reanimated it all went back to normal. Other than that lib is great!

**Comment by elyalvarado** [comment]
Hi @paskowski, thanks for reporting. react-native-reanimated is within the peer dependencies, which means your package manager (either npm or yarn) should have warned you about it missing. Its left as a peer dependency to allow people to install their own version and this package to use it. The same applies for react, react-native and react-navigation.
