### ISSUE TITLE
Update to react navigation 3.0

### ISSUE THREAD

**Issue by tn12787** [elyalvarado/react-navigation-switch-transitioner#8]
Since react navigation 3.0 you no longer need to call `createNavigationContainer` for custom navigators as this is wrapped at the top with a call to `createAppContainer`, [see here](https://reactnavigation.org/blog/2018/11/17/react-navigation-3.0.html#explicit-app-container-required-for-the-root-navigator) for an explanation on this.

In fact. `createNavigationContainer` is now deprecated, and is throwing me dev-level warnings. Can we get this removed?

**Comment by elyalvarado** [comment]
@tn12787 yes of course, I'll probably be releasing a new version this weekend and include this change.

**Comment by tn12787** [comment]
Excellent, thanks very much!

On 25 Jan 2019, at 4:56 PM, Ely Alvarado <notifications@github.com<mailto:notifications@github.com>> wrote:


@tn12787<https://github.com/tn12787> yes of course, I'll probably be releasing a new version this weekend and include this change.

**Comment by elyalvarado** [comment]
This is the new default. The old behavior is still available for users of older versions of react-navigation by importing and using `createContainedSwitchNavigator`
